[project]
name = "work-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tyf", email = "3103161568@qq.com" }
]
requires-python = ">=3.14"
dependencies = [
    "islp>=0.4.1",
    "pandas>=3.0.6",
    "statsmodels>=0.15.0",
]

[project.scripts]
work-1 = "work_1:main"

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
